### ISSUE TITLE
Won't run at all

### ISSUE THREAD

**Issue by Unfolds** [hectorgimenez/koolo#11]
Whenever I try to use the koolo.exe it will flash then nothing?

**Comment by hectorgimenez** [comment]
It might happen, maybe a panic, or any other random bug. You can try to check the log.txt (if it has been generated). In case is not generated, you can try to run the koolo.exe from the command line so you will be able to see the crash output and the console will not close after it

**Comment by Unfolds** [comment]
goroutine 50 [running]:
github.com/hectorgimenez/koolo/internal/reader/map_client.GetMapData({0xc000220240?, 0xc000454060?}, {0xc0001bb75c?, 0x0?})
        E:/projects/koolo/internal/reader/map_client/client.go:19 +0x3ac
github.com/hectorgimenez/koolo/internal/reader.(*GameReader).GetData(_, _)
        E:/projects/koolo/internal/reader/reader.go:27 +0xf8
github.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc00060c000, {0xc51970, 0xc0002fa050}, 0x1, {0xc000686000, 0x1, 0x1})
        E:/projects/koolo/internal/bot.go:47 +0xc5
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc00006c680, {0xc51970, 0xc0002fa050}, {0xc000686000, 0x1, 0x1})
        E:/projects/koolo/internal/single_supervisor.go:64 +0x29d
main.main.func2()
        E:/projects/koolo/cmd/koolo/main.go:90 +0xab
golang.org/x/sync/errgroup.(*Group).Go.func1()
        C:/Users/yast/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        C:/Users/yast/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa5

**Comment by hectorgimenez** [comment]
Yeah, there is no error control there, probably should be added some day. Also noticed that I should trimpath the binary... anyway, looks like your `D2LoDPath` param in `config.yaml` is not correctly pointing to your D2: LoD 1.13c directory.

**Comment by Unfolds** [comment]
Had to redownload another copy of D2Lod so got that all sorted now, thanks 

Few other issues,
1, native 1600x1200 resolution monitors, even though the game is set to 1280x720 it seems the mouse is completely out for example its 2 rows under the stash tabs when trying to click.
2. stashing items that aren't in the pickit list, butchers pupil etc etc
3. It got stuck for 5 hours with gloves in its hand in a1 xD

2023-07-19T00:54:47.422+0800	DEBUG	action/item_pickup.go:93	Item Detected: SharkskinGloves [4] at X:22540 Y:9538
2023-07-19T00:54:47.422+0800	DEBUG	step/pickup_item.go:56	Picking up: SharkskinGloves [Magic]
2023-07-19T00:54:48.147+0800	INFO	step/pickup_item.go:45	Item picked up: SharkskinGloves [Magic]
2023-07-19T00:54:48.183+0800	DEBUG	action/item_pickup.go:110	No items detected, waiting a bit and will try again	{"waitMs": 232}
2023-07-19T00:54:48.570+0800	INFO	internal/bot.go:106	Run Andariel finished, length: 44.29s
2023-07-19T00:55:00.026+0800	INFO	internal/supervisor.go:132	Starting Game #108. Run list: Eldritch, Andariel, Pindleskin
2023-07-19T00:55:00.026+0800	DEBUG	internal/bot.go:46	Fetching map data...
2023-07-19T00:55:01.091+0800	DEBUG	internal/bot.go:48	Fetch completed	{"ms": 1065}
2023-07-19T00:55:01.091+0800	INFO	internal/bot.go:54	Running: Eldritch
2023-07-19T00:55:01.135+0800	DEBUG	internal/bot.go:83	Loading screen detected, waiting until loading screen is gone
2023-07-19T00:55:03.381+0800	DEBUG	internal/bot.go:89	Load completed, continuing execution
2023-07-19T00:55:03.381+0800	DEBUG	action/recover_corpse.go:13	Checking for character corpse...
2023-07-19T00:55:03.381+0800	DEBUG	action/recover_corpse.go:38	Character corpse not found :D
2023-07-19T00:55:03.381+0800	DEBUG	action/identify.go:19	Checking for items to identify...
2023-07-19T00:55:03.381+0800	INFO	action/identify.go:25	Identifying 2 items...
2023-07-19T00:55:06.159+0800	DEBUG	action/stash.go:27	Checking for items to stash...
2023-07-19T00:55:06.159+0800	DEBUG	action/stash.go:29	No items to stash...
2023-07-19T00:55:06.159+0800	INFO	action/vendor_refill.go:15	Visiting vendor...
2023-07-19T01:03:20.056+0800	WARN	internal/single_supervisor.go:71	Game finished with errors, reason: max game length reached, try to exit game: 500.02. Game total time: 500.02s
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	C:/Users/yast/Desktop/koolo/internal/single_supervisor.go:71
main.main.func2
	C:/Users/yast/Desktop/koolo/cmd/koolo/main.go:90
golang.org/x/sync/errgroup.(*Group).Go.func1
	C:/Users/yast/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75

**Comment by hectorgimenez** [comment]
I never tried with that resolution, do you have any kind of screen scale or something? Also, the way this thing is calculating the game area is super hacky and the window borders are hardcoded, so maybe if you are using some kind of custom window theme or accesibility things making the UI bigger/smaller can be part of the problem. Looks like all your problems are related to the resolution.

**Comment by Unfolds** [comment]
That was on an alternative computer the 1600x1200 resolution so that isn't the standing still with items in hand issue, 2560x1440 is main resolution.

**Comment by hectorgimenez** [comment]
I have two computers, one is running Windows 11 in 3840x2160 (with hidpi), the other one (VM) is using Windows 10 with the very standard 1920x1080 resolution. I had no problem at all. The thing is that the way the application is getting the game area offset is a bit tricky and the window title bar offset is pretty much hardcoded, so if you are using like a custom windows theme or you have set different window title bar size probably can contribute to this problem. Didn't tried on multi monitor systems also, so if it's your case, I don't know how it will work
