### ISSUE TITLE
Fatal error on eldritch script

### ISSUE THREAD

**Issue by onyxbadge** [hectorgimenez/koolo#276]
### Details

After I updated the bot today it keeps having an error when running eldritch.
Any ideas

### Version

3e41e61

### Logs

time=00:24:17 level=DEBUG msg="Checking for items to stash..."
time=00:24:19 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=00:24:19 level=DEBUG msg="Load completed, continuing execution"
time=00:24:20 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=Pal error="runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 370 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0xad5380?, 0x1217a40?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/action.(*StepChainAction).IsFinished(0xc0007ce180?)\n\t<autogenerated>:1 +0x9\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc0007ce180, {0xdafba0, 0xc000b90050}, 0x0, {0xc000b07340, 0x2, 0x0?})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:162 +0x1051\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc000726038)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 24\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=00:24:20 level=INFO msg=Stopping... configuration=Pal
time=00:24:20 level=INFO msg="Finished stopping" configuration=Pal

**Comment by onyxbadge** [comment]
Not fixed it seems to be if the runs are done too fast. It's offline so not a bnet issue.
